export const allTowns = [
  { title: 'Барановичи', id: 0, rate: 5 },
  { title: 'Белоозерск', id: 1, rate: 4.75 },
  { title: 'Берёза', id: 2, rate: 4.45 },
  { title: 'Борисов', id: 3, rate: 3.85 },
  { title: 'Браслав', id: 4, rate: 3.45 },
  { title: 'Брест', id: 5, rate: 4.85 },
  { title: 'Витебск', id: 6, rate: 4.45 },
  { title: 'Гродно', id: 7, rate: 4.85 },
  { title: 'Дзержинск', id: 8, rate: 3.45 },
  { title: 'Жодино', id: 9, rate: 3.35 },
  { title: 'Лида', id: 10, rate: 4.45 },
  { title: 'Минск', id: 11, rate: 5 },
  { title: 'Могилёв', id: 12, rate: 4.35 },
  { title: 'Новогрудок', id: 13, rate: 4.6 },
  { title: 'Пинск', id: 14, rate: 4.85 },
  { title: 'Полоцк', id: 15, rate: 3.65 },
  { title: 'Рогачёв', id: 16, rate: 4.75 },
  { title: 'Слоним', id: 17, rate: 4.35 },
  { title: 'Слуцк', id: 18, rate: 4.15 },
];
